// <auto-generated />
namespace PGD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alteracaoUnidadeEUnidade_tipoPacto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteracaoUnidadeEUnidade_tipoPacto));
        
        string IMigrationMetadata.Id
        {
            get { return "202008191425035_alteracaoUnidadeEUnidade_tipoPacto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
